services:

  backend:
    build: ./project-backend
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate --no-input &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./project-backend:/app
      - media_data:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build: ./project-frontend
    command: npm run dev -- --host
    volumes:
      - ./project-frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  media_data: